services:
  - type: web
    name: tech-nova
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt && python myproject/manage.py collectstatic --noinput
    startCommand: gunicorn -c gunicorn_config.py myproject.wsgi
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.3
