# Generated by Django 6.0.2 on 2026-02-25 07:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sub_total', models.IntegerField(default=0)),
                ('shipping', models.IntegerField(default=0)),
                ('total_amount', models.IntegerField(default=0)),
                ('payment_id', models.CharField(blank=True, max_length=150)),
                ('payment_order_id', models.CharField(blank=True, max_length=150)),
                ('status', models.CharField(default='paid', max_length=20)),
                ('items_json', models.JSONField(default=list)),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.user')),
            ],
        ),
    ]
